from .home_page import homePage
from .single_type_page import singleTypePage
from .from_function_page import fromFunctionPage
from .explore_page import explorePage
from .artist_page import artistPage
from .search_page import searchPage
from .track_radio_page import trackRadioPage
from .playlist_page import playlistPage
from .start_up_page import startUpPage
from .not_logged_in_page import notLoggedInPage
from .mix_page import mixPage
from .album_page import albumPage
